import React from 'react';
import ReactDOM from 'react-dom/client';
import '@fontsource/pixelify-sans/latin-400.css';
import '@fontsource/pixelify-sans/latin-600.css';
import './styles/global.css';
import './styles/ui.css';
import './styles/home.css';
import './styles/site.css';
import App from './App';
import { LanguageProvider } from './i18n';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><LanguageProvider><App/></LanguageProvider></React.StrictMode>);
